name: Unit/Integration tests - Legacy

on:
  pull_request:
    branches:
      - trunk
      - develop

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2']
        wp-versions: ['5.2.9']
  
    name: WP ${{ matrix.wp-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mysqli
        coverage: none  # XDebug can be enabled here 'coverage: xdebug'
        tools: composer:v1
        
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start
    
    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Setup problem matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Remove unmet dependencies by legacy versions
      run: composer remove --dev coenjacobs/mozart phpstan/phpstan szepeviktor/phpstan-wordpress
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-scripts

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 ${{ matrix.wp-versions }}

    - name: Mysql8 auth plugin workaround
      run: sudo mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    - name: Test
      run: composer run-tests
      
